<a href="https://colab.research.google.com/github/poonamkhot123/Machine-Learning-Practice-Hub/blob/main/Day_28_Column_Transformer_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv("/content/covid_toy.csv")

In [11]:
df.head()

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No


In [12]:
df['cough'].value_counts()

,count
cough,
Mild,62
Strong,38


In [13]:
df['city'].value_counts()

,count
city,
Kolkata,32
Bangalore,30
Delhi,22
Mumbai,16


In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=["has_covid"]),df['has_covid'],test_size=0.2)

# 1.Aam Zindgadi

In [19]:
# adding simple imputer to fever columns
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

#  also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever

array([[103.        ],
       [100.        ],
       [104.        ],
       [101.        ],
       [104.        ],
       [100.        ],
       [101.        ],
       [ 99.        ],
       [102.        ],
       [103.        ],
       [ 98.        ],
       [102.        ],
       [ 98.        ],
       [ 99.        ],
       [101.        ],
       [101.        ],
       [100.90410959],
       [103.        ],
       [101.        ],
       [103.        ],
       [100.        ],
       [104.        ],
       [101.        ],
       [100.        ],
       [100.        ],
       [ 99.        ],
       [104.        ],
       [100.90410959],
       [ 98.        ],
       [101.        ],
       [100.        ],
       [ 98.        ],
       [101.        ],
       [104.        ],
       [ 99.        ],
       [ 98.        ],
       [102.        ],
       [101.        ],
       [ 98.        ],
       [104.        ],
       [101.        ],
       [100.90410959],
       [102.        ],
       [100

In [20]:
X_train_fever.shape

(80, 1)

In [21]:
# Ordinal encoding -> cough
oe = OrdinalEncoder(categories=[["Mild","Strong"]])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data.
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape


(80, 1)

In [22]:
X_train_cough

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],

In [26]:
# OneHotEncoding - > gender,city
ohe = OneHotEncoder(drop = 'first')
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [30]:
# Extracting age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_gender_city

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 85 stored elements and shape (80, 4)>

# Mentos Zindagi

In [35]:
from sklearn.compose import ColumnTransformer

In [36]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(drop='first'),['gender','city'])

], remainder ='passthrough')

In [37]:
transformer.fit_transform(X_train)

array([[103.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  83.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  80.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  18.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  20.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  51.        ],
       [100.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  27.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  19.        ],
       [ 99.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  65.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          0.    

In [38]:
transformer.fit_transform(X_train).shape

(80, 7)

In [40]:
transformer.transform(X_test).shape

(20, 7)