<a href="https://colab.research.google.com/github/poonamkhot123/Machine-Learning-Practice-Hub/blob/main/lecture_10_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

In [ ]:
a = np.array(4)

In [ ]:
a

array(4)

In [ ]:
a.ndim

0

In [ ]:
mat  = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
b = np.array([[1,2,3],[4,5,6]])

In [11]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
type(b)

numpy.ndarray

In [13]:
c = np.array([[3,4,5,6],[5,6,7,8]])


In [16]:
c

array([[3, 4, 5, 6],
       [5, 6, 7, 8]])

In [17]:
type(c)

numpy.ndarray